export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_COMPLETE = 'SIGN_IN_COMPLETE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const LOG_OUT_PENDING = 'LOG_OUT_PENDING';
export const LOG_OUT_COMPLETE = 'LOG_OUT_COMPLETE';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';
export const CREATE_ACCOUNT_PENDING = 'CREATE_ACCOUNT_PENDING';
export const CREATE_ACCOUNT_COMPLETE = 'CREATE_ACCOUNT_COMPLETE';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

// TODO: write action creators here